* Rule of...
- Rule of 5
  - if write destructor, also write [copy constructor, copy assignment op, mov constructor, mov assignment op]. Otherwise, destruction causes dangling references
- Rule of 0
  - if all member variables manage themselves (eg. vector, unique_ptr), write nothing

* Initialization
{} init avoid implicit conversion compared to = initialization.
Except for auto.
#+BEGIN_SRC 
int i = 7.8;	// i becomes 7
int i {7.8};	// error: floating-point to integer conversion
auto i = 7.8;	// no implicit conversion as auto retains the type as double
auto i {7.8};	// more consistent syntax

#+END_SRC

* Deducing types
  
** Template type deduction

In general:
- args with refs are treated as non-refs
- universal refs, lvalue args have special treatment
- by val params, const/volatile are treated as non-const/non-volatile
- array/function params decays to pointers unless param type is ref

#+BEGIN_SRC 
template<typename T>
void f(ParamType param);
// eg for ParamType: T, const T&, T&& etc

f(expr);	// deduce T and ParamType from expr

#+END_SRC
1) ParamType is ptr/ref, NOT universal ref
   - expr is ref, ignore the ref part
   - match expr's type against ParamType to determine T
   #+BEGIN_SRC 
template<typename T>
void f(T& param);

int x = 27;
const int cx = x;
const int& rx = x;

f(x);	// T int, param int&
f(cx);	// T const int, param const int&
f(rx);	// same as above

template<typename T>
void f(T* param);

int x = 27;
const int *px = &x;

f(x);	// T int, param int*
f(px);	// T const int, param const T*

   #+END_SRC

2) ParamType is universal ref
   - expr is lvalue, T/ParamType are lvalue ref
   - expr is rvalue, same as Case 1
   #+BEGIN_SRC 
template<typename T>
void f(T&& param);

int x = 27;
const int cx = x;
const int& rx = x;

f(x);	// T/param -> int&
f(cx);	// T/param -> const int&
f(rx);	// T/param -> const int&

f(27);	// T is int, param is int&&
   #+END_SRC

3) ParamType is NOT ptr/ref
   - if param is ref, ignore 
   - if param is const, ignore
   - if param is volatile, ignore
   #+BEGIN_SRC 
template<typename T>
void f(T param);

int x = 27;
const int cx = x;
const int& rx = x;

f(x);	// T/param -> int
f(cx);	// same as above
f(rx);	// same as above

const char* const ptr = "fun";

f(ptr);	// T/param -> const char*
   #+END_SRC

*** Array args for template type deduction
- in C and C++, array param decays to pointer
#+BEGIN_SRC 
cont char name[] = "John Chan";	// name's type is const char[10]
const char * ptrToName = name;	// ptrToName is const char*

template<typename T>
void f(T param);

f(name);	// T/name -> const char*; const char param[] decays is equivalent to const char* as params. Unfortunately decay behavior.

#+END_SRC
- However, reference to array is a different story
#+BEGIN_SRC 
template<typename T>
void f(T& param);

f(name);	// T is const char[10]; param is const char (&)[10]. Crazy syntax, ref to array size of 10 of const char.

#+END_SRC
- The above allows us to create compile time method to get array size at compile time.
#+BEGIN_SRC 
// no param name as we only care about the array size
template<typename T, std::size_t N>
constexpr std::size_t ArraySize(T (&)[N]) noexcept {	// noexcept helps compiler generate better code
	return N;
}

// can use to initialize array with same size as another
int keyVals[] = {1, 3, 4, 7};

int mappedVals[ArraySize(keyVals)];

std::array<int, ArraySize(keyVals)> mappedVals;

#+END_SRC

*** Function args for template type deduction
- same rule as array, functions decays to pointers
#+BEGIN_SRC 
void someFunc(int, double);	// type is void(int, double)

template<typename T>
void f(T param);

f(someFunc);	// T/param -> void (*)(int, double)

template<typename T>
void f(T& param);

f(someFunc);	// T/param -> void (&)(int, double)

// rarely makes any diff in practice

#+END_SRC


* Constants
constexpr - evaluated at compile time
constexpr functions
- can accept non-const args but the result is not a constexpr (so we don't need to duplicate a function for both constexpr and non constexpr use)
- cannot have side effects (no changes to non-local variables

* smart pointer
** shared_ptr
- make_shared(arg) is better than shared_ptr(new MyType(arg)) in most cases because
  - make_shared allocates the ptr with the ctl block in one single allocation while the other one involves 2 and not stored in samae place
  - ctl block is not deleted until last of shared_ptr ref and weak_ptr ref are gone
  - weak_ptr needs the shared_ptr ctrl block to know if ptr is still alive
  - sharedptr = make_shared(args...) may be better than shared_ptr.reset(new MyPtr(args...))

- weak_ptr ref shared_ptr and need to upgrade to shared_ptr before using it
- unique_ptr cannot be copied and cheaper than shared_ptr

* container
- std::array to replace c-style array
- prefer begin(container), end (container) than container.begin(), container.end() because it works on eg. array too.
* algorithm
** count & find
- count, count_if
- find, find_if, find_if_not, find_first_of
- search - find for a sub-sequence instead of single element
- find_end - WRONG naming but it actually searches for sub-sequence towards the end
- search_n - find for a val repeated n times (n times an element, not sequence), kind of odd naming
- adjacent_find - just return the first consecutive duplicate items

** sorting
- sort vs stable_sort
- upper_bound - 1st element from SORTED container > val
- lower_bound - 1st element from SORTED container <= val; can be used as a quicker find (uses binary search) than find but need to check for equality afterwards as it could be < val
- partial_sort
  - N (size), K (range size to sort)
  - useful for pagination where you only care about a certain range to be sorted
  - if K is not magnitudes < N, it could perform worse than sort
- partial_sort_copy - same as above but the result will be copy to a diff container
- nth_element - specify a partition point, all elements <= will be on the left, >= will be on the right
- shuffle
#+BEGIN_SRC 
# to use shuffle with random

#include <random>
random_device randdevice;

# mt19937 is a good generator, every "cool kids" use it :)
mt19937 generator{randdevice()};
shuffle(it1, it2, generator);

#+END_SRC
* lambda
#+BEGIN_SRC 
auto name = [capture clause](args...) -> ret_type { expr; }

[=] - auto smart capture *everything by value (everything is smart to only capture things used by the lambda)
[&] - auto smart catpure *everything by ref
[a, b, &c, &d] - catpures a and b by val, c and d by ref
ret_type (eg. double) - optional in case the compile failed to deduce the return type or deduce it wrong

#+END_SRC
* Misc
- variable can be defined in if statements and has scope for both if and else block
#+BEGIN_SRC 
if (auto x = v.size(); x != 0) {
	// works like for
}

if (auto x = v.size()) {
	// similar to above but implicit check for x != 0. Basically similar to if (x)
}

#+END_SRC

- std::mov(stuff) is just a cast to cast an lvalue to an rvalue
- noexcept declaration is needed on move constructor and move assignment operator to make them movable in stl containers
#+BEGIN_SRC 
Resource::Resource(Resource&& r) noexcept
: name(std::move(r.name))
{}

Resource& Resource::operator=(Resource&& r) noexcept {
	if (this != &r) {
		name = std::move(r.name);
		r.name.clear();
	}
	return *this;
}
#+END_SRC
